import Head from "next/head";

import HomeView from "@/components/home/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Booklog</title>
        <meta name="description" content="Generated by Booklog" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeView />
    </>
  );
}
